name: CircleCI artifacts redirector
on: 
  status:
  pull_request:
    branches: [ "main" ]

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  statuses: write

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    # For testing this action on a fork, remove the "github.repository =="" condition.
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLE_CI }}
          artifact-path: 0/doc_conf/index.html
          circleci-jobs: python3
          job-title: Check the rendered docs here!
  
  download-artifact:
    runs-on: ubuntu-latest
    needs: [circleci_artifacts_redirector_job]

    steps:

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get CircleCI Artifact URL
        id: get_artifact_url
        run: |
          CIRCLECI_TOKEN=${{ secrets.CIRCLECI_TOKEN }}
          CIRCLECI_PROJECT_SLUG="gh/lionelkusch/hidimstat"  
          CIRCLECI_BUILD_NUM=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/pipeline" | jq -r '.items[0].number')
          ARTIFACT_URL=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/$CIRCLECI_BUILD_NUM/artifacts" | jq -r '.items[0].url')
          echo "::set-output name=artifact_url::$ARTIFACT_URL"

      - name: Download Artifact
        run: |
          ARTIFACT_URL=${{ steps.get_artifact_url.outputs.artifact_url }}
          curl -L -o artifact.zip "$ARTIFACT_URL"
          unzip artifact.zip -d ./artifact

      - name: List Artifact Contents
        run: ls -R ./artifact

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: circleci-artifact
          path: ./artifact
  
  
  deploy_documentation:
        runs-on: ubuntu-latest
        needs: [download-artifact]
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v2

        -   name: Add SSH key
            env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            run: |
                mkdir -p ~/.ssh
                ssh-keyscan github.com >> ~/.ssh/known_hosts
                echo "${{ secrets.ACTIONS_SSH_DEPLOY }}" > ~/.ssh/github_actions
                chmod 600 ~/.ssh/github_actions
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                ssh-add ~/.ssh/github_actions

        -   uses: actions/download-artifact@v4
            with:
                name: circleci-artifact
                path: ./html

        -   name: deploy
            env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                COMMIT_SHA: ${{ github.event.head_commit.id }}
            run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub actions"
                ./build_tools/circle/push_doc.sh